development:
  adapter: mysql2
  encoding: utf8
  database: test_task
  username: root
  password: "140283"

production:
  adapter: mysql2
  encoding: utf8
  database: test_task
  username: root
  password: "140283"
